# Generated by Django 5.0.6 on 2024-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('DOB', models.IntegerField()),
                ('States', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Course', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
