# Generated by Django 5.0.6 on 2024-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTRAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Mail', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_Password', models.CharField(max_length=50)),
            ],
        ),
    ]
